-- To: sawada@sra.co.jp
-- Cc: mikami@is.s.u-tokyo.ac.jp, yas@yk.is.noda.sut.ac.jp,
--         joker@sy.is.noda.sut.ac.jp
-- Subject: Re: parser 
-- In-reply-to: Your message of "Tue, 02 Sep 1997 15:12:20 JST."
-- Mime-Version: 1.0 (generated by tm-edit 7.106)
-- Date: Thu, 18 Sep 1997 20:58:31 +0900
-- From: Masaki Ishiguro <masa@mri.co.jp>
-- Content-Type: text/plain; charset=ISO-2022-JP
-- Content-Length: 1733


-- 澤田様:

-- 下記の件ですが,  CafeOBJ system Version 1.3.1(Roman) で試したところ, 
-- 同じエラーとなりました.  Version 1.3.b7は正しく動くのですが, その版に
-- は psup-unparse-expression が含まれないため, 同時につかうことが出来ま
-- せん. 
-- ご確認頂けますでしょうか. 
-- --
-- 石黒

-- >> To: sawada@sra.co.jp
-- >> Subject: parser

-- >> CafeOBJパーザの件ですが, CafeOBJ system Version 1.3.1 で 
-- >> psup-image-of-axioms を以下の仕様で使おうとしましたところ, エラーとなっ
-- >> てしまいます. 前の版では, psup-image-of-axioms の動作を確認していたの
-- >> ですが. 調べて頂けないでしょうか. 
-- >> 
-- >> ------------------------------------------------------------------
-- >> 
-- >> 
mod TOSET {
  [ Elt ]
  op _<_ : Elt Elt -> Bool
  vars E1 E2 E3 : Elt
  eq E1 < E1 = false .
  cq E1 < E3 = true if (E1 < E2) and (E2 < E3) .
  cq (E1 < E2) or (E2 < E1) = true if E1 =/= E2 .
}

mod NAT' {
  [ Nat ]
  op 0 : -> Nat
  op s : Nat -> Nat
  op _+_ : Nat Nat -> Nat 
  op _<_ : Nat Nat -> Bool
  vars m n : Nat
  eq m + 0 = m .
  eq m + s(n) = s(m + n) .
  eq 0 < s(n) = true .
  eq n < 0 = false .
  eq s(n) < s(m) = n < m .
  
}

view F from TOSET to NAT' {
  sort Elt -> Nat
  op _<_ -> _<_
}
 
-- ------------------------------------------------------------------
--  CafeOBJ> in view-obl
--  -- processing input : ./view-obl.mod
--  -- defining module TOSET..._...* done.
--  -- defining module NAT'......_.....* done.
--  -- defining view F  done.
 
--  CafeOBJ> evq (psup-image-of-axioms "F")
--  Broken at PSUP-IMAGE-OF-AXIOMS.  Type :H for Help.
--  CHAOS>>

