(in-package "conditions")

(defun compare-semantics (file condition)
  (let ((results))
  (load (format nil "~A.lisp" file))
  (push (with-output-to-string (s) (princ condition s)) results)
  (compile-file (format nil "~A.lisp" file))
  (load (format nil "~A.o" file))
  (push (with-output-to-string (s) (princ condition s)) results)
  (print (reverse results))
  (values)))